# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-31 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438')),
            ],
            options={
                'db_table': 'category',
                'verbose_name': '\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Galary_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galary_image', models.ImageField(blank=True, upload_to='galary/img', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
            ],
            options={
                'db_table': 'galary_image',
                'verbose_name': '\u0413\u0430\u043b\u0438\u0440\u0435\u044f',
                'verbose_name_plural': '\u0413\u0430\u043b\u0438\u0440\u0435\u0438',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(max_length=100, verbose_name='\u0423\u0434\u043e\u0431\u0441\u0442\u0432\u0430')),
            ],
            options={
                'db_table': 'info',
                'verbose_name': '\u0423\u0434\u043e\u0431\u0441\u0442\u0432\u0430',
                'verbose_name_plural': '\u0423\u0434\u043e\u0431\u0441\u0442\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='Realty_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realty_name', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('vid_name', models.CharField(blank=True, help_text='\u0412\u0438\u0434 \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438 \u043d\u0430 \u043f\u0440\u0438\u043c\u0435\u0440 \u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439', max_length=100, verbose_name='\u0432\u0438\u0434')),
                ('tip_name', models.CharField(blank=True, help_text='\u0422\u0438\u043f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c', max_length=100, verbose_name='\u0422\u0438\u043f')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u0446\u0435\u043d\u0430')),
                ('sale_and_rental', models.CharField(blank=True, help_text='\u041f\u0440\u043e\u0434\u0430\u0436\u0430 \u0438\u043b\u0438 \u0430\u0440\u0435\u043d\u0434\u0430', max_length=100, verbose_name='\u0414\u043b\u044f')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d')),
                ('bedrooms', models.IntegerField(default=0, verbose_name='\u0421\u043f\u0430\u043b\u044c\u043d\u0438')),
                ('rooms', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043c\u043d\u0430\u0442')),
                ('bathrooms', models.IntegerField(default=0, verbose_name='\u0421\u0430\u043d\u0443\u0437\u043b\u044b')),
                ('area', models.IntegerField(default=0, verbose_name='\u043f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('land_area', models.IntegerField(default=0, verbose_name='\u043f\u043b\u043e\u0449\u0430\u0434\u044c \u0443\u0447\u0430\u0441\u0442\u043a\u0430')),
                ('from_the_sea', models.IntegerField(default=0, verbose_name='\u043e\u0442 \u043c\u043e\u0440\u044f')),
                ('floor', models.IntegerField(default=0, verbose_name='\u042d\u0442\u0430\u0436')),
                ('garash', models.IntegerField(default=0, verbose_name='\u0413\u0430\u0440\u0430\u0436')),
                ('room_id', models.IntegerField(default=0, verbose_name='\u041d\u043e\u043c\u0435\u0440 ID')),
                ('date', models.DateField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430')),
                ('brief_description', models.TextField(blank=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f')),
                ('body', models.TextField(blank='True', verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f')),
                ('description', models.TextField(blank=True, help_text='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u044f \u0434\u043b\u044f \u043f\u043e\u0438\u0441\u043a\u0430 \u042f\u043d\u0434\u0435\u043a\u0441 \u0438 googla \u0441\u043b\u043e\u0432\u0430 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u0442 \u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e', max_length=100, verbose_name='\u0414\u0438\u0441\u043a\u0440\u0438\u043f\u0448\u0438\u043d')),
                ('keywords', models.TextField(blank=True, help_text='\u041a\u043b\u044e\u0447\u0438\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430 \u0434\u043b\u044f \u043f\u043e\u0438\u0441\u043a\u0430 \u042f\u043d\u0434\u0435\u043a\u0441 \u0438 googla \u0441\u043b\u043e\u0432\u0430 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u0442 \u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e', max_length=100, verbose_name='\u041a\u043b\u044e\u0447\u0438\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430')),
                ('main_image', models.ImageField(blank=True, upload_to='main_image/img', verbose_name='\u0424\u043e\u0442\u043e \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0438')),
                ('published', models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0430\u0433\u0435\u043d\u0442')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.Category', verbose_name='\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
                ('page_info', models.ManyToManyField(blank=True, help_text='\u0427\u0442\u043e \u0435\u0441\u0442\u044c \u0432 \u0434\u043e\u043c\u0435', to='realty.Info', verbose_name='\u0423\u0434\u043e\u0431\u0441\u0442\u0432\u0430')),
            ],
            options={
                'db_table': 'realty_page',
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b',
            },
        ),
        migrations.AddField(
            model_name='galary_image',
            name='realty_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.Realty_Page'),
        ),
    ]
