# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galary_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galary_image', models.ImageField(blank=True, upload_to='galary/img', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('realty_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.Realty_Page')),
            ],
            options={
                'db_table': 'galary_image',
                'verbose_name': '\u0413\u0430\u043b\u0438\u0440\u0435\u044f',
                'verbose_name_plural': '\u0413\u0430\u043b\u0438\u0440\u0435\u0438',
            },
        ),
    ]
