# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-05 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import realty.models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galary_image',
            name='galary_image',
            field=models.ImageField(blank=True, upload_to=realty.models.get_file_galary, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='realty_page',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=realty.models.get_file_path, verbose_name='\u0424\u043e\u0442\u043e \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0438'),
        ),
    ]
