# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-22 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty_page',
            name='garash',
            field=models.IntegerField(default=0, verbose_name='\u0413\u0430\u0440\u0430\u0436'),
        ),
    ]
