# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-05 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190605_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty_page',
            name='published',
            field=models.BooleanField(default=True, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d'),
        ),
    ]
