# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-10 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_realty_page_garash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galary_image',
            name='realty_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.Realty_Page'),
        ),
    ]
