# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-22 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_auto_20190510_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty_page',
            name='published',
            field=models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d'),
        ),
    ]
