# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-04 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mame',
            new_name='name',
        ),
    ]
